from src.prompts.base_prompts import BasePrompt

class MultiGrammarErrorCorrectionGenerationPrompt(BasePrompt):
    template: str = """Korrigiere den folgenden Text, indem du ihn grammatikalisch korrekt gestaltest.
Korrigiere alle Rechtschreib-, Interpunktions-, Stil-, Grammatik-, Lexik- und Syntaxfehler.
Falls keine Fehler vorhanden sind, gib den Originaltext unverändert wieder.
Erstelle {num_corrections} verschiedene Varianten des korrigierten Textes mit Erklärungen.
Escapiere in der Antwort alle doppelten Anführungszeichen und andere spezielle Zeichen mittels zweier Backslashes.
Beispielsweise: Verwende statt eines Zeilenumbruchs den String \\n; statt " den String \\".
Bitte entfernen Sie keine technischen Symbole wie Internetlinks, Tags usw. aus anderen Sprachen (hauptsächlich Englisch).


Antwortformat in JSON:
[{{
    "correction": "korrigierter Text",
    "explanation": "Erklärung zur Korrektur"
}}, ...]

Beispiele:

1. Eingangstext:
   Abs . Frau EVA SCHMIDT BAHNHOFSTR , 8-12 , 1234 STADT X LITAUEN AUPAIRSGLOBAL BAHNHOFSTR : 101 , 65185 WIESBADEN 0611 / 9988776 STADT X , 14.05.2011 SEHR GEEHRTE DAMEN UND HERREN ICH HABE IHRE ANZEIGE GELESEN ; UND WOLTE NOCH EIN PAAR FRAGEN STELEN . ICH HABE LITAUISCHE STAATSANGEHORISCHKEIT : WIE IST MIT AUFENTHALTSFORMALITÄTEN ? ( LITAUEN IST IN den EU ) : BRAUCHE ICH " EINE ABITUR DIPLOME und ec : DOKUMENTE ZU UBERSETZEN ? WIE LANG DAUERT die GANZE POWEREITUNG mit -unreadable- WO ICH SOLLTE MICH MELDEN WEGEN ARBEITSGENEHMIGUNG ( in mein Heimatsland oder in Deutschland ) Ich wolte wisen , welche Sprache wird in der Familie geschprochen . Ich möchte gern in Deutsche Familie arbeiten - um meine Deutsch sprache zu verbesern . ( Englisch spreche ich nicht ) Noch ein paar Fragen : - Wie viele Stunde am Tag würde ich Arbeiten ? - wan Kinder sind in die Schuhle , oder in der KITA , darf ich meine Zeit selbst organizieren ( Einkaufen , Putzen , Ordnung machen - oder gibs eine feste Zeitplan ) - Dürfte ich eine Deutschsprache Kurse besuschen ? Gibs in Eurere Statd solche Kurse ? ? ? - Muss ich 24 St am Tag mit Familie verbringen ? Ich gerne schwimmen ( das tut gut für Stresausbau ) , dürfte ich das auch in Deutschland machen ? Ich warte auf ihre Antwort , und bin bereit ab mitte Mai nach Deutschland abreiten . Schöne Gruße Frau Eva Schmidt

   Korrektur:
   [("Abs. Frau Eva Schmidt Bahnhofstr. 8-12, 1234 STADT X, Litauen Aupairsglobal Bahnhofstr. 101, 65185 WIESBADEN, 0611/9988776 STADT X, 14.05.2011 Sehr geehrte Damen und Herren, ich habe Ihre Anzeige gelesen und wollte noch ein paar Fragen stellen. Ich besitze die litauische Staatsangehörigkeit: Wie ist es mit den Aufenthaltsformalitäten? (Litauen ist Mitglied der EU): Muss ich Abiturzeugnisse, Diplome und weitere Dokumente übersetzen lassen? Wie lange dauert die gesamte Vorbereitung mit -unreadable-? Wo sollte ich mich wegen einer Arbeitsgenehmigung melden – in meinem Heimatland oder in Deutschland? Ich würde gerne wissen, welche Sprache in der Familie gesprochen wird. Ich möchte in einer deutschen Familie arbeiten, um meine Deutschkenntnisse zu verbessern (Englisch spreche ich nicht). Noch ein paar Fragen: - Wie viele Stunden am Tag würde ich arbeiten? - Wenn die Kinder in der Schule oder in der Kita sind, darf ich meine Zeit selbst organisieren (Einkaufen, Putzen, Ordnung machen – oder gibt es einen festen Zeitplan)? - Darf ich an einem Deutschkurs teilnehmen? Gibt es in Ihrer Stadt solche Kurse? - Muss ich 24 Stunden am Tag mit der Familie verbringen? Ich schwimme sehr gerne (das tut dem Stressabbau gut); dürfte ich auch in Deutschland schwimmen? Ich warte auf Ihre Antwort und bin bereit, ab Mitte Mai in Deutschland zu arbeiten.", "Anpassung von Rechtschreibung, Interpunktion, Grammatik und Stil zur Verbesserung der Lesbarkeit und Formalität."),
   ("Abs. Frau Eva Schmidt, Bahnhofstr. 8-12, 1234 STADT X, Litauen Aupairsglobal, Bahnhofstr. 101, 65185 WIESBADEN, 0611/9988776 STADT X, 14.05.2011. Sehr geehrte Damen und Herren, ich habe Ihre Anzeige gelesen und möchte einige Fragen stellen. Ich habe die litauische Staatsangehörigkeit. Wie verhält es sich mit den Aufenthaltsformalitäten? (Litauen ist Mitglied der EU.) Muss ich Abiturzeugnisse, Diplome und weitere Dokumente übersetzen lassen? Wie lange dauert die gesamte Vorbereitung mit -unreadable-? Wo muss ich mich wegen einer Arbeitsgenehmigung melden – in meinem Heimatland oder in Deutschland? Ich würde gerne wissen, welche Sprache in der Familie gesprochen wird. Ich möchte in einer deutschen Familie arbeiten, um meine Deutschkenntnisse zu verbessern (ich spreche kein Englisch). Weitere Fragen: - Wie viele Stunden täglich würde ich arbeiten? - Wenn die Kinder in der Schule oder in der Kita sind, kann ich meine Zeit selbst organisieren (Einkaufen, Putzen, Ordnung machen – oder gibt es einen festen Zeitplan)? - Ist es möglich, an einem Deutschkurs teilzunehmen? Gibt es in Ihrer Stadt solche Kurse? - Muss ich den ganzen Tag, also 24 Stunden, mit der Familie verbringen? Ich schwimme gerne (das tut dem Stressabbau gut); dürfte ich auch in Deutschland schwimmen? Ich warte auf Ihre Antwort und bin ab Mitte Mai bereit, in Deutschland zu arbeiten.", "Alternative Formulierung zur Verbesserung der Struktur und Verständlichkeit.")]

2. Eingangstext:
   Katharina Winkelmann Müllergasse 12 12345 Stadt X 06.03.2010 Computer-Spezialist Odenwaldstraße 5 , m 53119 Bonn Bewerbung für Vertriebspraktikum . Ich lebe seit 4 Jahren in Deutschland . Ich bin Studentin als Betriebswirtschaftslehre an der XY Universität in Stadt Y und Ich will in Deutschland weiter Studieren . Ich möchte gerne dieses Vertriebspraktikum in Ihrem Haus absolvieren , weil ich mich für an elektronischer Datenverarbeitung interessiere . Ich kann gut mit andere Leute zusammen arbeiten Ich lerne gerne neues dazu . Ich kann sehr gut mit Computer arbeiten und ich kenne officeprogramme sehr gut . Ich kann flexibel arbeiten . Ich freue mich sehr über ein vorstellungsspräch . Mit freundlichen Grüßen Katharina Winkelmann

   Korrektur:
   [("Katharina Winkelmann, Müllergasse 12, 12345 Stadt X, 06.03.2010, Computer-Spezialist, Odenwaldstraße 5, 53119 Bonn. Bewerbung für ein Vertriebspraktikum. Ich lebe seit 4 Jahren in Deutschland. Ich studiere Betriebswirtschaftslehre an der XY Universität in Stadt Y und möchte in Deutschland weiter studieren. Ich würde dieses Vertriebspraktikum in Ihrem Unternehmen gerne absolvieren, weil ich mich für elektronische Datenverarbeitung interessiere. Ich kann gut mit anderen Menschen zusammenarbeiten, lerne gerne Neues dazu, arbeite sehr gut mit dem Computer und kenne Office-Programme sehr gut. Ich bin flexibel einsetzbar und freue mich sehr über ein Vorstellungsgespräch. Mit freundlichen Grüßen, Katharina Winkelmann.", "Korrektur von Rechtschreibung, Grammatik und Stil zur Anpassung an den deutschen Standard."),
   ("Katharina Winkelmann, Müllergasse 12, 12345 Stadt X, 06.03.2010, Computer-Spezialist, Odenwaldstraße 5, 53119 Bonn. Bewerbung um ein Vertriebspraktikum. Seit 4 Jahren lebe ich in Deutschland. Als Studentin der Betriebswirtschaftslehre an der XY Universität in Stadt Y möchte ich mein Studium in Deutschland fortsetzen. Ich interessiere mich sehr für elektronische Datenverarbeitung und möchte deshalb gerne ein Vertriebspraktikum in Ihrem Haus absolvieren. Ich arbeite gerne im Team, lerne schnell Neues, beherrsche den Umgang mit Computern und bin mit Office-Programmen bestens vertraut. Ich bin flexibel und freue mich auf ein persönliches Vorstellungsgespräch. Mit freundlichen Grüßen, Katharina Winkelmann.", "Alternative Formulierung zur Verbesserung der Klarheit und Professionalität.")]

3. Eingangstext:
   Maria Müller Stadt X , 05.03.2010 Zentralplatz 12 12345 Stadt X Mobil : 012344567 Computer-Spezialist Odenwaldstraße 5 53119 Bonn Bewerbung um Praktikumsplatz als IT-Systemkauffrau Sehr geehrte Damen und Herren , hiermit möchte ich mich um einen Praktikumsplatz bei Ihnen bewerben . Ihr Unternehmen hat in mir echtes Interesse und auch große Neugier hervorgerufen . Zurzeit absolviere ich Abitur , vorher habe ich Hauptschule abschluss gemacht mit der Gesamtnote 1,6 . Aufgrund meiner bisher durchgeführten Praktika ( siehe Lebenslauf ) verfüge ich bereits über viel Erfahrung im Wirtschaftshandelbereich und einige Erfahrungen im Einzelhandelbereich . Ich sehe eine Herausforderung , bei der ich mich engagieren kann und der ich mich gewachsen fühle . Ihr Unternehmen arbeitet mit verschiedenen Unternehmen aus der ganzen Welt , so könnte ich meine Englisch- , Russisch- und Deutschkenntnisse anwenden und perfektionieren . Mit mir finden Sie eine zuverlässige Praktikantin , eine Teamplayerin , die dennoch ihrer Position entsprechend diskret und loyal ist . Darüber hinaus hoffe ich , meine bisher erworbenen Kenntnisse während eines Praktikums einbringen zu können . Ich möchte dieses Praktikum gerne ab sofort anfangen . Über die Einladung zu einem persönlichen Gespräch würde ich mich sehr freuen . Mit freundlichen Grüßen Maria Müller Anlagen : Lebenslauf , Zeugnisse in Kopie

   Korrektur:
   [("Maria Müller, Stadt X, 05.03.2010, Zentralplatz 12, 12345 Stadt X, Mobil: 012344567, Computer-Spezialist, Odenwaldstraße 5, 53119 Bonn. Bewerbung um einen Praktikumsplatz als IT-Systemkauffrau. Sehr geehrte Damen und Herren, hiermit bewerbe ich mich um einen Praktikumsplatz in Ihrem Unternehmen. Ihr Unternehmen hat mein echtes Interesse und große Neugier geweckt. Zurzeit absolviere ich mein Abitur; zuvor habe ich einen Hauptschulabschluss mit der Gesamtnote 1,6 erworben. Aufgrund meiner bisherigen Praktika (siehe Lebenslauf) verfüge ich über umfangreiche Erfahrungen im Wirtschaftshandel sowie im Einzelhandel. Ich sehe in Ihrem Unternehmen eine Herausforderung, bei der ich mich engagieren kann und der ich gewachsen bin. Ihr Unternehmen arbeitet mit verschiedenen Firmen weltweit zusammen, sodass ich meine Englisch-, Russisch- und Deutschkenntnisse anwenden und verbessern kann. Mit mir gewinnen Sie eine zuverlässige, teamorientierte Praktikantin, die diskret und loyal agiert. Darüber hinaus hoffe ich, meine bisherigen Kenntnisse während eines Praktikums einbringen zu können. Ich würde gerne ab sofort beginnen. Über eine Einladung zu einem persönlichen Gespräch würde ich mich sehr freuen. Mit freundlichen Grüßen, Maria Müller. Anlagen: Lebenslauf, Zeugnisse (Kopie).", "Anpassung von Rechtschreibung, Grammatik, Interpunktion und Stil zur Erhöhung der Formalität und Klarheit."),
   ("Maria Müller, Stadt X, 05.03.2010, Zentralplatz 12, 12345 Stadt X, Mobil: 012344567, Computer-Spezialist, Odenwaldstraße 5, 53119 Bonn. Bewerbung um einen Praktikumsplatz als IT-Systemkauffrau. Sehr geehrte Damen und Herren, ich bewerbe mich hiermit um einen Praktikumsplatz in Ihrem Unternehmen. Ihr Unternehmen hat bei mir echtes Interesse und Neugierde geweckt. Derzeit absolviere ich mein Abitur; zuvor schloss ich die Hauptschule mit der Note 1,6 ab. Durch meine bisherigen Praktika (siehe Lebenslauf) habe ich umfangreiche Erfahrungen im Wirtschaftshandel und Einzelhandel gesammelt. Ich sehe in Ihrem Unternehmen eine Herausforderung, bei der ich mein Engagement einbringen kann. Da Ihr Unternehmen mit internationalen Partnern zusammenarbeitet, kann ich meine Sprachkenntnisse in Englisch, Russisch und Deutsch optimal einsetzen und weiterentwickeln. Sie erhalten mit mir eine zuverlässige, teamfähige Praktikantin, die diskret und loyal agiert. Ich hoffe, meine erworbenen Kenntnisse während eines Praktikums einbringen zu können und würde mich über ein persönliches Gespräch freuen. Mit freundlichen Grüßen, Maria Müller. Anlagen: Lebenslauf, Zeugnisse (Kopie).", "Alternative Formulierung zur Verbesserung der Lesbarkeit und Formalität.")]

4. Eingangstext:
   Sehr geehrter Damen und Herren , Ich habe Ihnen Anzeige über die Vertriebspraktikum gesucht gelesen . Ich bin Architekturstudenten und auf diesemn Grund interessiere mich viel dieses Praktikum . Ich meine , dass für mich eine wunderware Erfahrung wäre , wenn ich an dieser Firma teilnehmen könnte . Ich kann alle Sachen was Sie möchten machen . Ich bin in dem letzten Semester von meiner Karriere und ich hatte die beste Qualifikation was ich kann . Ich kann auch sofort beginnen . Auf jeden fall möchte ich nur wissen , wie viele Geld verdiene ich und wie viele Stunden müsste ich pro Woche arbeiten . Ich hoffe , dass Sie mit mir möchten arbeiten werden . Ich glaube , dass ich viele positive Sachen und guten Erfahrungen lernen kann . Vielen danke Mit freundlichen Grüßen , Michael Winkelmann

   Korrektur:
   [("Sehr geehrte Damen und Herren, ich habe Ihre Anzeige über ein Vertriebspraktikum gelesen. Ich bin Architekturstudent und interessiere mich daher sehr für dieses Praktikum. Ich bin der Meinung, dass es für mich eine wunderbare Erfahrung wäre, wenn ich in Ihrem Unternehmen tätig sein könnte. Ich bin bereit, alle Aufgaben zu übernehmen, die Sie mir übertragen. Da ich mich im letzten Semester meines Studiums befinde und über ausgezeichnete Qualifikationen verfüge, kann ich auch sofort beginnen. Ich würde jedoch gerne wissen, wie viel Gehalt gezahlt wird und wie viele Stunden pro Woche zu arbeiten sind. Ich hoffe, dass Sie Interesse an einer Zusammenarbeit mit mir haben. Ich bin überzeugt, dass ich viele positive Erfahrungen und wertvolle Kenntnisse sammeln kann. Vielen Dank. Mit freundlichen Grüßen, Michael Winkelmann.", "Korrektur von Rechtschreibung, Grammatik, Satzbau und Ausdruck zur Verbesserung der Verständlichkeit und Professionalität."),
   ("Sehr geehrte Damen und Herren, ich habe Ihre Anzeige für ein Vertriebspraktikum gelesen. Als Architekturstudent interessiere ich mich sehr für diese Stelle und bin überzeugt, dass es für mich eine hervorragende Erfahrung wäre, in Ihrem Unternehmen mitzuwirken. Ich bin in der Lage, sämtliche von Ihnen gewünschten Aufgaben zu erfüllen, und befinde mich im letzten Semester meines Studiums, was meine Flexibilität und Qualifikation unterstreicht. Ich könnte sofort beginnen. Allerdings möchte ich gerne wissen, wie hoch das Gehalt ist und wie viele Stunden pro Woche gearbeitet werden müssen. Ich freue mich auf Ihre Rückmeldung und eine mögliche Zusammenarbeit. Mit freundlichen Grüßen, Michael Winkelmann.", "Alternative Formulierung zur Verbesserung von Stil und Höflichkeit.")]

5. Eingangstext:
   Eva Meier Zentralplatz 1 12345 Stadt X Computer-Spezialist Odenwaldstraße 5 53119 Bonn Betreff : Bewerbung als Praktikantin Stadt X 22 , Marz 2010 Sehr geehrte Damen und Herren , Mit großem Interesse habe ich Ihre Anzeige in der Zeitung gelessen . Sie suchen eine leistungsfähige Praktikantin für den Verkauf in Ihre Geschäft . Deshalb möchte ich mich um diese Stelle Bewerben . Nach einem Erfolgreichen Abschluß meines Studiums in Betriebswissenschaften hätte ich gern meine Kenntnisse erweitern . Ich habe in meinem Studium nicht nur über die Grundlagen des Verkaufs gelernt sondern auch über Informatik . Ich habe seh viel interesse für elektronischer Datenverarbeitung . Und bin über Computers sehr begeistert . Ich bin Single deshalb verfüge ich über Flexibilität und Mobilität Ich erwarte meine fähigkeiten und kenntnisse in Ihre . Firma zu erweitern . Über einem persönlichen gespräch würde ich mich sehr freuen , damit Sie sich einem besseren eindruck von mir machen konnen . Die Stelle kann ich bereits ab den 23 . Marz 2010 anfangen . Mit freundlichen Grüßen , Eva Meier

   Korrektur:
   [("Eva Meier, Zentralplatz 1, 12345 Stadt X, Computer-Spezialist, Odenwaldstraße 5, 53119 Bonn. Betreff: Bewerbung als Praktikantin in Stadt X, 22. März 2010. Sehr geehrte Damen und Herren, mit großem Interesse habe ich Ihre Anzeige in der Zeitung gelesen. Sie suchen eine leistungsfähige Praktikantin für den Verkauf in Ihrem Geschäft, weshalb ich mich hiermit bewerbe. Nach einem erfolgreichen Abschluss meines Studiums der Betriebswissenschaften würde ich meine Kenntnisse gern weiter vertiefen. In meinem Studium habe ich nicht nur die Grundlagen des Verkaufs, sondern auch Informatik gelernt. Ich habe großes Interesse an elektronischer Datenverarbeitung und bin von Computern sehr begeistert. Da ich ledig bin, verfüge ich über Flexibilität und Mobilität. Ich erhoffe mir, meine Fähigkeiten und Kenntnisse in Ihrem Unternehmen einbringen zu können. Über ein persönliches Gespräch würde ich mich sehr freuen, damit Sie sich einen besseren Eindruck von mir machen können. Die Stelle könnte ich bereits ab dem 23. März 2010 antreten. Mit freundlichen Grüßen, Eva Meier.", "Korrektur der Rechtschreibung, Grammatik, Interpunktion und Stil zur Anpassung an den deutschen Standard."),
   ("Eva Meier, Zentralplatz 1, 12345 Stadt X, Computer-Spezialist, Odenwaldstraße 5, 53119 Bonn. Betreff: Bewerbung als Praktikantin in Stadt X, 22. März 2010. Sehr geehrte Damen und Herren, mit großem Interesse habe ich Ihre Zeitungsanzeige gelesen. Sie suchen eine kompetente Praktikantin für den Verkauf in Ihrem Geschäft. Deshalb bewerbe ich mich um diese Position. Nach einem erfolgreichen Abschluss meines Studiums der Betriebswirtschaft würde ich meine Kenntnisse gerne erweitern. Neben den Grundlagen des Verkaufs habe ich auch Informatik studiert. Mein Interesse an elektronischer Datenverarbeitung ist sehr groß, und ich bin von Computern begeistert. Da ich ledig bin, bin ich flexibel und mobil. Ich bin überzeugt, dass ich meine Fähigkeiten und Kenntnisse optimal in Ihrem Unternehmen einsetzen kann. Über eine Einladung zu einem persönlichen Gespräch würde ich mich sehr freuen. Die Stelle kann ich bereits ab dem 23. März 2010 antreten. Mit freundlichen Grüßen, Eva Meier.", "Alternative Formulierung zur Verbesserung von Klarheit und formeller Sprache.")]

Eingangstext: {text}
Korrektur:"""


class GrammarErrorCorrectionAggregationPrompt(BasePrompt):
    template: str = """Aggregiere die vorgeschlagenen grammatikalischen Korrekturen des Textes zu einem finalen, grammatikalisch korrekten Text.
Aus dem Originaltext und einer Liste von {num_corrections} Varianten seiner Korrektur, vereine alle sinnvollen Korrekturen dieser Varianten und erstelle den final korrigierten, syntaktisch korrekten Text.
Entferne Rechtschreib-, Interpunktions-, Stil-, Grammatik-, Lexik- und Syntaxfehler.
Füge Erklärungen zu den aggregierten Korrekturen und zur grammatikalischen Textkorrektur hinzu.
Konzentriere dich auf die vorgeschlagenen Korrekturen und versuche nicht, den Originaltext eigenständig zu korrigieren.
Falls keine Fehler vorhanden sind, gib den Originaltext unverändert zurück.
Escapiere in der Antwort alle doppelten Anführungszeichen und andere spezielle Zeichen mittels zweier Backslashes.
Beispielsweise: Verwende statt eines Zeilenumbruchs den String \\n; statt " den String \\\".
Bitte entfernen Sie keine technischen Symbole wie Internetlinks, Tags usw. aus anderen Sprachen (hauptsächlich Englisch).


Format der vorgeschlagenen Korrekturen:
[{{
    "correction": "korrigierter Text",
    "explanation": "Erklärung zur Korrektur"
}},...]

[Output only JSON]
Antwortformat in JSON:
{{
    "correction": "korrigierter Text",
    "explanation": "Erklärung zur Korrektur"
}}

Originaltext: {text}
Vorgeschlagene Korrekturen: {possible_corrections}
Korrigierter Text:"""
    input_variables: list[str] = ["text", "possible_corrections", "num_corrections"]

